
SET feed OFF
SET timi OFF
COL member FOR a100

PROMPT
PROMPT
PROMPT Actual Log Files:

SELECT group#, members, status, bytes/1024/1024 as "Size (MB)" from v$log;

SELECT * from v$logfile;

--ALTER SYSTEM SWITCH LOGFILE
--ALTER SYSTEM CHECKPOINT

--ALTER DATABASE DROP LOGFILE GROUP 3
--ALTER DATABASE ADD LOGFILE GROUP 3 'C:\APP\ORACLE\ORADATA\ORAPIU\REDO03.RDO' size 500M

SET feed ON
SET timi ON
