
/* EXIBE O PLANO DE EXECUCAO ARMAZENADO PELO AWR DADO UM SQL_ID */

SET verify OFF

SELECT * FROM table(DBMS_XPLAN.DISPLAY_AWR('&sql_id',NULL,NULL,'ADVANCED'))
/

UNDEFINE sql_id

SET verify ON