
BREAK ON REPORT 
COMPUTE SUM OF PERC ON REPORT
COL perc HEAD "% DB" FOR 9.999

WITH size_database 
AS
( SELECT SUM(bytes) AS size_database FROM dba_segments )
SELECT segment_name
,      ROUND(SUM(bytes)/1024/1024,2) AS MB 
,      ROUND((SUM(bytes)/size_database)*100,4) AS PERC
  FROM dba_segments
,      size_database  
 WHERE segment_name IN (
'T_PS_CONSULTORA',
'PRE_CADASTRO_CNO',
'T_PS_INTENCAO_REVENDA',
'T_DOCUMENTO_PESSOA',
'T_PS_DADO_COMPLEMENTAR',
'T_PS_DADO_COMPLEMENTAR_DOMINIO',
'T_PS_DADO_COMPLEMENTAR_PESSOA',
'T_TIPO_LOGRADOURO',
'T_PS_ZONEAMENTO_ENTREGA',
'T_PS_CEP_ZONEAMENTO_ENTREGA',
'T_PS_RESTRICAO_REVENDA',
'T_PS_SPC',
'T_PS_TIPO_RESTRICAO',
'T_PS_CHEQUE_DEVOLVIDO',
'T_AGENCIA',
'T_ACEITE_CONDICOES_COMERCIAIS',
'T_PS_CRIANCA_PESSOA',
'ESTRUTURA_ZONEAMENTO',
'T_CONSULTORA_TRP_BCO',
'T_PS_COLABORADOR',
'ATUALIZACAO_FREQUENTE',
'DOMINIO_CAMPO_LOG',
'DOMINIO_TABELA_LOG',
'TIPO_ATUALIZACAO_FREQUENTE',
'LOG_ALTERACAO_CADASTRAL',
'T_CICLO_OPERACIONAL',
'T_PESSOA_RELACAO_COMERCIAL',
'T_PS_MOTIVO_BLOQUEIO',
'T_PS_HISTORICO_BLOQUEIO',
'T_ENDERECO_PESSOA',
'T_PESSOA_FISICA',
'T_ESTRUTURA_COMERCIAL',
'T_PS_PAPEL_PESSOA',
'T_TIPO_ESTRUTURA_COMERCIAL',
'T_TIPO_ATIVIDADE_PROFISSIONAL',
'T_PS_TIPO_PAPEL',
'T_TELEFONE_PESSOA',
'T_COMUNICADO',
'T_GRUPO_COMUNICADO',
'T_PAPEL_COMUNICADO',
'T_PESSOA',
'T_EMAIL_PESSOA',
'T_COMUNICADO_PESSOA')
GROUP BY segment_name
,        size_database
ORDER BY segment_name;
